### ISSUE TITLE
Exclude Filesystem

### ISSUE THREAD

**Issue by rolikeusch** [Addvilz/gullveig#1]
Is it possible to exclude a Filesystem? If you have snapd installed you will see some fs that are with 0% free space.

![filesystem](https://user-images.githubusercontent.com/3592156/91178797-f7f2b880-e6e5-11ea-8db0-3112581b6ce3.png)

**Comment by Addvilz** [comment]
No, you can't exclude a file system right now.

The underlying issue is that Gullveig now monitors all available block devices and mounts indiscriminately - this should not be the case and should be handled in mod_fs gracefully, say - there is absolutely no need for these snap mounts to be monitored (they are fixed virtual block devices).

Let me look into this and see how to best deal with this, but I suspect I will make the problem "go away" auto-magically.

**Comment by rolikeusch** [comment]
Ah ok. Then i hope you will find some auto-magically way ;)

**Comment by Addvilz** [comment]
Fixed with 0.1.6. SquashFS (used by snap and other similar things) will be ignored, as it makes little sense to monitor file system that is read-only. Normally, the squash usage will be part of host usage so. 

There is another option to in section `[mod_fs]` called `ignore_ro`, by default true - to ignore read only systems completely. This is to deal with mounts that are read only from host but should still be monitored as they might not be mounted ro somewhere else.

**Comment by rolikeusch** [comment]
looks good!
