### ISSUE TITLE
Install only the Agent

### ISSUE THREAD

**Issue by rolikeusch** [Addvilz/gullveig#3]
will it be possible to install only the agent? if i install with pip now i get also the web and server part on the client. but i don't need this on an agent.

**Comment by Addvilz** [comment]
This is by design - some parts of the code are reused between agent, server, web and util components - eventually there will be more (ex. database abstraction, logging, etc). Another thing is - eventually, there will be more parts to the agent, that are not running as agent and by default (ex. `pam_exec` executable to capture authentication events for audit and alert). Basically, having it all in one package makes the whole thing easier to manage, publish and maintain.

Is there a practical reason you want separate installs?

**Comment by rolikeusch** [comment]
the reason is just to save space and not to install anything that is not needed ;)
but I understand your reasons.

**Comment by Addvilz** [comment]
Yeah in that case I will keep them separate for now. Who knows, if the bundle grows too large, I might split them apart at some point, but not an immediate goal.
